import { NextPage } from 'next';
import Head from 'next/head';

const NewDisclosure: NextPage = () => {
  return (
    <>
      <Head>
        <title>Disclosures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container flex flex-col items-center justify-center gap-12 px-2 py-16 ">
        Hi
      </div>
    </>
  );
};

export default NewDisclosure;
